# Generated by Django 2.1.3 on 2018-12-18 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceapp', '0003_auto_20181218_1043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='p_invoice',
            name='id',
        ),
    ]
