# Generated by Django 2.1.3 on 2018-12-31 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceapp', '0009_auto_20181221_0546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='p_invoice',
            name='date',
            field=models.DateField(),
        ),
    ]
